force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Progress_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Progress_Tracker__c</fullName>
    <label>Progress Tracker</label>
    <referenceTo>Progress_Tracker__c</referenceTo>
    <relationshipLabel>Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Week_1__c.field-meta.xml
<CustomField>
    <fullName>Week_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Week 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Week_2__c.field-meta.xml
<CustomField>
    <fullName>Week_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Week 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Week_3__c.field-meta.xml
<CustomField>
    <fullName>Week_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Week 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Week_4__c.field-meta.xml
<CustomField>
    <fullName>Week_4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Week 4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Week_5__c.field-meta.xml
<CustomField>
    <fullName>Week_5__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Week 5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Week_6__c.field-meta.xml
<CustomField>
    <fullName>Week_6__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Week 6</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Week_7__c.field-meta.xml
<CustomField>
    <fullName>Week_7__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Week 7</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Week_8__c.field-meta.xml
<CustomField>
    <fullName>Week_8__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Week 8</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/Weekly_Goal__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Goal__c</fullName>
    <label>Weekly Goal</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/MentorAmp_User__c.object-meta.xml
<CustomObject>
    <label>MentorAmp User</label>
    <nameField>
        <displayFormat>MU-{0000000000}</displayFormat>
        <label>MentorAmp User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MentorAmp Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MentorAmp_User__c/fields/MentorAmp_User__c.field-meta.xml
<CustomField>
    <fullName>MentorAmp_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MentorAmp User</label>
    <referenceTo>MentorAmp_User__c</referenceTo>
    <relationshipLabel>MentorAmp Users</relationshipLabel>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/fields/Progress_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Progress_Tracker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Progress Tracker</label>
    <referenceTo>Progress_Tracker__c</referenceTo>
    <relationshipLabel>MentorAmp Users</relationshipLabel>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/recordTypes/Mentee.recordType-meta.xml
<RecordType>
    <fullName>Mentee</fullName>
    <active>true</active>
    <label>Mentee</label>
</RecordType>

force-app/main/default/objects/Progress_Tracker__c/Progress_Tracker__c.object-meta.xml
<CustomObject>
    <label>Progress Tracker</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Progress Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Tracker__c/fields/Current_Week__c.field-meta.xml
<CustomField>
    <fullName>Current_Week__c</fullName>
    <defaultValue>&quot;week1&quot;</defaultValue>
    <label>Current Week</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/mainComponentController.cls
public inherited sharing class mainComponentController {

    @AuraEnabled(cacheable=true)
    public static String getMentorAmpUser () {
        Id currentUserId = UserInfo.getUserId();
        Id menteeRecordTypeId = Schema.SObjectType.MentorAmp_User__c.getRecordTypeInfosByName().get('Mentee').getRecordTypeId();
        Id mentorRecordTypeId = Schema.SObjectType.MentorAmp_User__c.getRecordTypeInfosByName().get('Mentor').getRecordTypeId();
        List<MentorAmp_User__c> mtUsers = [SELECT Id, Name, User__c, Progress_Tracker__c, RecordTypeId FROM MentorAmp_User__c WHERE User__c = :currentUserId];
        if (mtUsers.size() == 0){
            return 'notSignedUp';
        } else if (mtUsers.size() == 1 && mtUsers[0].RecordTypeId == menteeRecordTypeId) {
            return 'onlyMentee';
        } else if (mtUsers.size() == 1 && mtUsers[0].RecordTypeId == mentorRecordTypeId) {
            return 'onlyMentor';
        } else if (mtUsers.size() > 1) {
            return 'both';
        } else {
            return 'error';
        }
    }

    @AuraEnabled(cacheable=true)
    public static String getMentorName () {
        Id currentUserId = UserInfo.getUserId();
        Id menteeRecordTypeId = Schema.SObjectType.MentorAmp_User__c.getRecordTypeInfosByName().get('Mentee').getRecordTypeId();
        List<MentorAmp_User__c> currentMentees = [SELECT Id, Name, User__c, Progress_Tracker__c, RecordTypeId, MentorAmp_User__c FROM MentorAmp_User__c WHERE User__c = :currentUserId AND RecordTypeId = :menteeRecordTypeId];
        List<MentorAmp_User__c> mentors = [SELECT Id, Name, Name__c FROM MentorAmp_User__c WHERE Id = :currentMentees[0].MentorAmp_User__c];
        if (mentors.size() == 0) {
            return 'No mentor has been assigned yet';
        } else {
            return mentors[0].Name__c;
        }
    }

    @AuraEnabled(cacheable=true)
    public static String getMenteeName () {
        Id currentUserId = UserInfo.getUserId();
        Id mentorRecordTypeId = Schema.SObjectType.MentorAmp_User__c.getRecordTypeInfosByName().get('Mentor').getRecordTypeId();
        List<MentorAmp_User__c> currentMentors = [SELECT Id, Name, User__c, Progress_Tracker__c, RecordTypeId, MentorAmp_User__c FROM MentorAmp_User__c WHERE User__c = :currentUserId AND RecordTypeId = :mentorRecordTypeId];
        List<MentorAmp_User__c> mentees = [SELECT Id, Name, Name__c, MentorAmp_User__c FROM MentorAmp_User__c WHERE MentorAmp_User__c = :currentMentors[0].Id];
        if (mentees.size() == 0) {
            return 'No mentee has been assigned yet';
        } else {
            return mentees[0].Name__c;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Category__c> getMenteeCategories() {
        Id currentUserId = UserInfo.getUserId();
        Id menteeRecordTypeId = Schema.SObjectType.MentorAmp_User__c.getRecordTypeInfosByName().get('Mentee').getRecordTypeId();
        MentorAmp_User__c mentee = [SELECT Id, Name, User__c, Progress_Tracker__c, RecordTypeId FROM MentorAmp_User__c WHERE User__c = :currentUserId AND RecordTypeId = :menteeRecordTypeId];
        List<Category__c> categories = [
            SELECT Id, Name, Weekly_Goal__c, Week_1__c, Week_2__c, Week_3__c, Week_4__c, Week_5__c, Week_6__c, Week_7__c, Week_8__c
            FROM Category__c
            WHERE Progress_Tracker__c = :mentee.Progress_Tracker__c
            WITH SECURITY_ENFORCED
        ];
        return categories;
    }

    @AuraEnabled(cacheable=true)
    public static String getCurrentWeek () {
        Id currentUserId = UserInfo.getUserId();
        Id menteeRecordTypeId = Schema.SObjectType.MentorAmp_User__c.getRecordTypeInfosByName().get('Mentee').getRecordTypeId();
        List<MentorAmp_User__c> currentMentees = [SELECT Id, Name, User__c, Progress_Tracker__c, RecordTypeId, MentorAmp_User__c FROM MentorAmp_User__c WHERE User__c = :currentUserId AND RecordTypeId = :menteeRecordTypeId];
        Progress_Tracker__c tracker = [SELECT Id, Name, Current_Week__c FROM Progress_Tracker__c WHERE Id = :currentMentees[0].Progress_Tracker__c];
        String currentWeek = tracker.Current_Week__c;
        return currentWeek;
    }

    @AuraEnabled
    public static String updateCurrentWeek (String newWeek) {
        Id currentUserId = UserInfo.getUserId();
        Id menteeRecordTypeId = Schema.SObjectType.MentorAmp_User__c.getRecordTypeInfosByName().get('Mentee').getRecordTypeId();
        List<MentorAmp_User__c> currentMentees = [SELECT Id, Name, User__c, Progress_Tracker__c, RecordTypeId, MentorAmp_User__c FROM MentorAmp_User__c WHERE User__c = :currentUserId AND RecordTypeId = :menteeRecordTypeId];
        Progress_Tracker__c tracker = [SELECT Id, Name, Current_Week__c FROM Progress_Tracker__c WHERE Id = :currentMentees[0].Progress_Tracker__c];
        tracker.Current_Week__c = newWeek;
        try {
            update tracker;
            return 'Success: Progress Tracker updated successfully';
        } 
        catch (Exception e) {
            return 'The following exception has occurred: ' + e.getMessage();
        }
    }
}