force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Progress_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Progress_Tracker__c</fullName>
    <label>Progress Tracker</label>
    <referenceTo>Progress_Tracker__c</referenceTo>
    <relationshipLabel>Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/MentorAmp_User__c.object-meta.xml
<CustomObject>
    <label>MentorAmp User</label>
    <nameField>
        <displayFormat>MU-{0000000000}</displayFormat>
        <label>MentorAmp User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MentorAmp Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MentorAmp_User__c/fields/MentorAmp_User__c.field-meta.xml
<CustomField>
    <fullName>MentorAmp_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MentorAmp User</label>
    <referenceTo>MentorAmp_User__c</referenceTo>
    <relationshipLabel>MentorAmp Users</relationshipLabel>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/fields/Progress_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Progress_Tracker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Progress Tracker</label>
    <referenceTo>Progress_Tracker__c</referenceTo>
    <relationshipLabel>MentorAmp Users</relationshipLabel>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/recordTypes/Mentee.recordType-meta.xml
<RecordType>
    <fullName>Mentee</fullName>
    <active>true</active>
    <label>Mentee</label>
</RecordType>

force-app/main/default/objects/Progress_Tracker__c/Progress_Tracker__c.object-meta.xml
<CustomObject>
    <label>Progress Tracker</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Progress Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Tracker__c/fields/Current_Week__c.field-meta.xml
<CustomField>
    <fullName>Current_Week__c</fullName>
    <defaultValue>&quot;week1&quot;</defaultValue>
    <label>Current Week</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestFactory.cls
public with sharing class TestFactory {
    
    public static User insertTestUser () {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1]; 
        User testUser = new User(Alias = 'standt', Email='mentoramp@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='mentoramp@testorg.com');
        insert testUser;
        return testUser;
    }

    public static User insertTestUser2 () {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1]; 
        User testUser2 = new User(Alias = 'standt', Email='mentoramp@testorg2.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='mentoramp@testorg2.com');
        insert testUser2;
        return testUser2;
    }

    public static void insertTestData () {
        User testUser = insertTestUser();
        User testUser2 = insertTestUser2();
        Id menteeRecordTypeId = Schema.SObjectType.MentorAmp_User__c.getRecordTypeInfosByName().get('Mentee').getRecordTypeId();
        Id mentorRecordTypeId = Schema.SObjectType.MentorAmp_User__c.getRecordTypeInfosByName().get('Mentor').getRecordTypeId();

        Progress_Tracker__c pgTrack1 = new Progress_Tracker__c(Current_Week__c = 'week2');
        insert pgTrack1;
        Category__c category1 = new Category__c (Name = 'Test Category', Progress_Tracker__c = pgTrack1.Id);
        insert category1;

        Progress_Tracker__c pgTrack2 = new Progress_Tracker__c(Current_Week__c = 'week3');
        insert pgTrack2;
        Category__c category2 = new Category__c (Name = 'Test Category2', Progress_Tracker__c = pgTrack2.Id);
        insert category2;

        MentorAmp_User__c firstMentorUser = new MentorAmp_User__c (User__c = testUser.Id, RecordTypeId = mentorRecordTypeId, Name__c = 'First Mentor');
        insert firstMentorUser;
        MentorAmp_User__c firstMenteeUser = new MentorAmp_User__c (User__c = testUser.Id, RecordTypeId = menteeRecordTypeId, Progress_Tracker__c = pgTrack1.Id, Name__c = 'First Mentee');
        insert firstMenteeUser;
        MentorAmp_User__c secondMenteeUser = new MentorAmp_User__c (User__c = testUser2.Id, RecordTypeId = menteeRecordTypeId, MentorAmp_User__c = firstMentorUser.Id, Progress_Tracker__c = pgTrack2.Id, Name__c = 'Second Mentee');
        insert secondMenteeUser;
    }
}