force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Progress_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Progress_Tracker__c</fullName>
    <label>Progress Tracker</label>
    <referenceTo>Progress_Tracker__c</referenceTo>
    <relationshipLabel>Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/MentorAmp_User__c.object-meta.xml
<CustomObject>
    <label>MentorAmp User</label>
    <nameField>
        <displayFormat>MU-{0000000000}</displayFormat>
        <label>MentorAmp User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MentorAmp Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MentorAmp_User__c/fields/MentorAmp_User__c.field-meta.xml
<CustomField>
    <fullName>MentorAmp_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MentorAmp User</label>
    <referenceTo>MentorAmp_User__c</referenceTo>
    <relationshipLabel>MentorAmp Users</relationshipLabel>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/fields/Progress_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Progress_Tracker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Progress Tracker</label>
    <referenceTo>Progress_Tracker__c</referenceTo>
    <relationshipLabel>MentorAmp Users</relationshipLabel>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Tracker__c/Progress_Tracker__c.object-meta.xml
<CustomObject>
    <label>Progress Tracker</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Progress Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/datatableControllerTest.cls
@isTest
public class datatableControllerTest {
    
    @isTest
    public static void getCategoriesTest() {
        List<User> userList = [SELECT Id, Name FROM User];
        User testUser = userList[0];
        System.runAs(testUser) {
            Progress_Tracker__c pgTrack = new Progress_Tracker__c();
            insert pgTrack;
            
            MentorAmp_User__c mtUser = new MentorAmp_User__c (Progress_Tracker__c = pgTrack.Id, User__c = testUser.Id);
            insert mtUser;
            
            Category__c category = new Category__c (Name = 'Test Category', Progress_Tracker__c = pgTrack.Id);
            insert category;
            
            List<Category__c> categories = datatableController.getCategories();
            System.assert(categories.size() != 0);
        }
    }
    
    @isTest
    public static void updateCategoriesTest() {
        Progress_Tracker__c pgTrack = new Progress_Tracker__c();
        insert pgTrack;
        
		Category__c cat1 = new Category__c (Name = 'Cat1', Progress_Tracker__c = pgTrack.Id);
        Category__c cat2 = new Category__c (Name = 'Cat2', Progress_Tracker__c = pgTrack.Id);
		List<Category__c> catList = new List<Category__c>();
        catList.add(cat1);
        catList.add(cat2);
        insert catList;
        
        System.debug(datatableController.updateCategories(catList));
    }
    
    @isTest
    public static void getProgressTrackerTest() {
        List<User> userList = [SELECT Id, Name FROM User];
        User testUser = userList[0];
        System.runAs(testUser) {
            Progress_Tracker__c pgTrack = new Progress_Tracker__c();
            insert pgTrack;
            
            MentorAmp_User__c newMtUser = new MentorAmp_User__c (Progress_Tracker__c = pgTrack.Id, User__c = testUser.Id);
            insert newMtUser;
            
            List<MentorAmp_User__c> mtUser = [SELECT Id, Name FROM MentorAmp_User__c WHERE User__c = :testUser.Id];
            if (mtUser.size() == 1) {
                System.assertEquals(pgTrack.Id, datatableController.getProgressTracker());
            } else {
                System.assert(mtUser.size() > 1);
            }
            
        }
        
    }
    
    @isTest
    public static void createCategoryTest() {
        List<User> userList = [SELECT Id, Name FROM User];
        User testUser = userList[0];
        System.runAs(testUser) {
            Progress_Tracker__c pgTrack = new Progress_Tracker__c();
            insert pgTrack;
            
            MentorAmp_User__c newMtUser = new MentorAmp_User__c (Progress_Tracker__c = pgTrack.Id, User__c = testUser.Id);
            insert newMtUser;
            
            System.assertEquals('Success: category created successfully', datatableController.createCategory('Test name', 'Test goal'));
        }
    }
    
    @isTest
    public static void deleteCategoryTest() {
        Progress_Tracker__c pgTrack = new Progress_Tracker__c();
        insert pgTrack;
		Category__c category = new Category__c (Name = 'Test Category', Progress_Tracker__c = pgTrack.Id);
        insert category;
        System.assertEquals('Success: categories deleted successfully', datatableController.deleteCategory(category.Id));
    }
}