force-app/main/default/objects/MentorAmp_User__c/MentorAmp_User__c.object-meta.xml
<CustomObject>
    <label>MentorAmp User</label>
    <nameField>
        <displayFormat>MU-{0000000000}</displayFormat>
        <label>MentorAmp User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MentorAmp Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MentorAmp_User__c/fields/MentorAmp_User__c.field-meta.xml
<CustomField>
    <fullName>MentorAmp_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MentorAmp User</label>
    <referenceTo>MentorAmp_User__c</referenceTo>
    <relationshipLabel>MentorAmp Users</relationshipLabel>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/fields/Progress_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Progress_Tracker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Progress Tracker</label>
    <referenceTo>Progress_Tracker__c</referenceTo>
    <relationshipLabel>MentorAmp Users</relationshipLabel>
    <relationshipName>MentorAmp_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorAmp_User__c/recordTypes/Mentee.recordType-meta.xml
<RecordType>
    <fullName>Mentee</fullName>
    <active>true</active>
    <label>Mentee</label>
</RecordType>

force-app/main/default/objects/Progress_Tracker__c/Progress_Tracker__c.object-meta.xml
<CustomObject>
    <label>Progress Tracker</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Progress Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MentorUserController.cls
public with sharing class MentorUserController {
    @AuraEnabled
    public static void saveUserRecord(MentorAmp_User__c user) {
        Id menteeRecordTypeId = Schema.SObjectType.MentorAmp_User__c.getRecordTypeInfosByName().get('Mentee').getRecordTypeId();
        if(user != null){
            if (user.RecordTypeId == menteeRecordTypeId) {
                Progress_Tracker__c pgTrack = new Progress_Tracker__c();
                insert pgTrack;
                user.Progress_Tracker__c = pgTrack.Id;
            }
            insert user;
        } 
    }
}